#!/bin/bash

set -eu

BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
VCS_REF=$(git rev-parse --short HEAD)
IMAGE_NAME="${DOCKER_REPO}:${CACHE_TAG}"

docker build \
  --build-arg BUILD_DATE=$BUILD_DATE \
  --build-arg VCS_REF=$VCS_REF \
  --tag $IMAGE_NAME ./
